"""Add new column to contacts

Revision ID: 230cbaaac8b4
Revises: 
Create Date: 2025-02-23 01:58:39.641027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '230cbaaac8b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_stalks_id', table_name='user_stalks')
    op.drop_table('user_stalks')
    op.drop_table('spatial_ref_sys')
    op.alter_column('messages', 'sender_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('messages_sender_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['candidate_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_sender_id_fkey', 'messages', 'users', ['sender_id'], ['id'])
    op.alter_column('messages', 'sender_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.create_table('user_stalks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stalker_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stalked_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stalk_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stalked_id'], ['users.candidate_id'], name='user_stalks_stalked_id_fkey'),
    sa.ForeignKeyConstraint(['stalker_id'], ['users.candidate_id'], name='user_stalks_stalker_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_stalks_pkey')
    )
    op.create_index('ix_user_stalks_id', 'user_stalks', ['id'], unique=False)
    # ### end Alembic commands ###
